### ISSUE TITLE
Fix insertion

### ISSUE THREAD

**Issue by moCello** [dusk-network/merkle#27]
**Describe the bug**
when items get inserted at random positions, the `child_index` returned by `child_location` is wrong.

**To Reproduce**
in src/lib.rs:
```rust
#[cfg(test)]
mod tests {
    use super::*;
    use rand::rngs::StdRng;
    use rand::{RngCore, SeedableRng};

    const HEIGHT: usize = 17;
    const ARITY: usize = 4;

    type BigTree = Tree<u64, HEIGHT, ARITY>;

    impl Aggregate<HEIGHT, ARITY> for u64 {
        const EMPTY_SUBTREES: [Self; HEIGHT] = [0; HEIGHT];

        fn aggregate<'a, I>(items: I) -> Self
        where
            Self: 'a,
            I: Iterator<Item = &'a Self>,
        {
            *items.into_iter().max().unwrap()
        }
    }

    #[test]
    fn tree_insertion_random() {
        let mut tree = BigTree::new();
        let rng = &mut StdRng::seed_from_u64(0xdea1);

        for item in 0..1000 {
            tree.insert(rng.next_u64(), item as u64);
        }
    }
}
```

**Expected behaviour**
The tree is big enough to insert leaves at any position smaller than `u64::MAX` so this test should pass.

**Logs/Screenshot**
![Screenshot_2023-05-12_17-04-24](https://github.com/dusk-network/merkle/assets/46872249/fbdaea8e-6947-4fcc-b5b5-a01a052ab8ea)

**Comment by ureeves** [comment]
This tree has height `17` and arity `4`, so it has `4^17` positions. This is much smaller than `u64::MAX`. The first position this test tries to insert into is `5964061510349134267`, which is larger than the capacity of the tree - `17179869184`.

The panic message could be better but as far as I can see this *should panic*. What am I missing :confused:?

**Comment by moCello** [comment]
You're right! In my head I remembered that we chose the height of `17` so we can have the largest tree where the positions are representable with `u64` but that seemed to be incorrect information lingering in my head! Closing this issue
