### ISSUE TITLE
`insert` can panic due to Out of Bounds

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/merkle#91]
**Describe the bug**
The `insert` method can panic

**To Reproduce**
?

**Expected behaviour**
`insert` should never panic

**Logs/Screenshot**

```
index out of bounds: the len is 2 but the index is 2
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/0f44eb32f1123ac93ab404d74c295263ce468343/library/core/src/panicking.rs:190:5
   3: dusk_merkle::node::Node<T,_,_>::insert
   4: dusk_consensus::merkle::merkle_root
```

**Additional context**
At a first glance, the issue stems from not asserting that the `position` argument is within the range of leaves.
As a consequence, if this argument is too large, `child_location` can return an out-of-bound index, causing the panic.

**Comment by ureeves** [comment]
It is untrue to say that insertion should never panic - it *should* panic on an out of bounds insertion. However, I agree that the message is not exactly proper to what is happening. #92 addresses this by introducing an explicit bounds check on insertion.
